theme: jekyll-theme-minimal
title: Bin Lu (卢彬)
logo: /images/Robin-newyear.jpg
description: "PhD Student
  <br>Department of Electronic Engineering
  <br>Shanghai Jiao Tong University
  <br>
  <br>Office: 441 SEIEE No.1 Building
  <br>Email: robinlu1209@sjtu.edu.cn
  <br>
  <br><a href=\"https://scholar.google.com/citations?user=HsI7HPoAAAAJ&hl=zh-CN&oi=sra\">Google Scholar</a>
  <br><a href=\"https://github.com/RobinLu1209\">Github</a>"
  <br><a href=\"https://www.linkedin.cn/injobs/in/bin-robin-lu-a9b661142\">LinkedIn</a>"
email: robinlu1209@sjtu.edu.cn
google_analytics:
