theme: jekyll-theme-minimal
title: Bin Lu (卢彬)
logo: /images/lubin_island.jpeg
description: "PhD Student
  <br>Department of Electronic Engineering
  <br>Shanghai Jiao Tong University
  <br>
  <br>Office: 441 SEIEE No.1 Building
  <br>Email: robinlu1209@sjtu.edu.cn
  <br>
  <br><a href=\"https://scholar.google.com/citations?user=HsI7HPoAAAAJ&hl=zh-CN&oi=sra\">Google Scholar</a>
  <br><a href=\"https://dblp.uni-trier.de/pid/48/7036-5.html\">DBLP</a>
  <br><a href=\"https://www.semanticscholar.org/author/2064914349\">Semantic Scholar</a>
  <br><a href=\"https://github.com/RobinLu1209\">Github</a>"
  <br><a href=\"https://github.com/RobinLu1209/robinlu1209.github.io/blob/master/files/CV_BinLu.pdf\">CV</a>"
email: robinlu1209@sjtu.edu.cn
google_analytics:
